-- List Builder for X-Wing 2.0
-- ~~~~~~
-- Script by Johnny Cheese
--
-- This module creates a set of buttons and text input on an object.
-- Script has 3 main modules: FFG spawner, TTS spawner and Squad Builder.
-- FFG spawner receives the link for a saved FFG web site squad and spawns said squad.
-- TTS spawner receives a string containingthe name of all pilots and upgrades and set up a table wich will be passed to the global newSpawner function.
-- Squad Builder offers options to build a squad, but does not apply any restrictions other than faction specific cards.
-- The cards with the same name are diferentiated by faction when possible, and will if needed, the script inquires the player wich version is being summoned.
-- The inquire happens in cases of pilots on the same faction using different ships (Sabine, Ezra, "Zeb") and in cases of upgrades with the same name (R2-D2 crew and astromech)
-- ~~~~~~


self.interactable = false


-- List and cost of variable cost upgrades based on base sizea
varCostS={}
varCostS[296] = {[1] = 2, [2] = 4,[3] = 7} --Engine Upgrade
varCostS[234] = {[1] = 2, [2] = 4,[3] = 6} --Expert Handling
varCostS[489] = {[1] = 3, [2] = 6,[3] = 9} --Hate
varCostS[612] = {[1] = 7, [2] = 8,[3] = 9} --Snap Shot

-- List and cost of variable cost upgrades based on agility value
varCostA={}
varCostA[282] = {[0] = 3,[1] = 5,[2] = 7,[3] = 9} --R2 Astromech
varCostA[297] = {[0] = 2,[1] = 3,[2] = 5,[3] = 7} --Hull Upgrade
varCostA[299] = {[0] = 3,[1] = 4,[2] = 6,[3] = 8} --Shield Upgrade
varCostA[301] = {[0] = 3,[1] = 4,[2] = 6,[3] = 8} --Stealth Device
varCostA[315] = {[0] = 4,[1] = 6,[2] = 8,[3] = 10} --R2-D2 (Astromech)

varCostI={}
varCostI[245]={[0]=2,[1]=4,[2]=6,[3]=8,[4]=10,[5]=12,[6]=14} --Squad Leader
varCostI[246]={[0]=3,[1]=3,[2]=3,[3]=3,[4]=3,[5]=4,[6]=5} --Swarm Tactics
varCostI[276]={[0]=2,[1]=3,[2]=4,[3]=5,[4]=6,[5]=7,[6]=8} --Seasoned Navigator
varCostI[290]={[0]=0,[1]=1,[2]=2,[3]=3,[4]=4,[5]=5,[6]=6} --Inertial Dampeners
varCostI[463]={[0]=4,[1]=5,[2]=6,[3]=7,[4]=8,[5]=9,[6]=10} -- Primed Thrusters
varCostI[251]={[0]=4,[1]=4,[2]=4,[3]=8,[4]=16,[5]=24,[6]=32} --Supernatural Reflexes
varCostI[479]={[0]=2,[1]=3,[2]=4,[3]=5,[4]=6,[5]=7,[6]=8} -- BB8
varCostI[480]={[0]=0,[1]=1,[2]=2,[3]=3,[4]=4,[5]=5,[6]=6} -- bb astromech
varCostI[545]={[0]=0,[1]=2,[2]=4,[3]=6,[4]=8,[5]=10,[6]=12} -- Battle Meditation
varCostI[548]={[0]=14,[1]=15,[2]=16,[3]=17,[4]=18,[5]=19,[6]=20} -- Delta-7B
varCostI[549]={[0]=0,[1]=0,[2]=1,[3]=2,[4]=3,[5]=5,[6]=5} -- Calibrated laser Targeting
varCostI[614]={[0]=3,[1]=3,[2]=3,[3]=4,[4]=7,[5]=10,[6]=13} -- Precognitive Reflexes
varCostI[610]={[0]=12,[1]=12,[2]=12,[3]=12,[4]=14,[5]=21,[6]=28} -- Ensnare

--tables referenced by upgrades that adds actions to ships
addAction={}
addAction[294]={[1]='B'} --Afterbuners
addAction[231]={[1]='Dare'} --Daredevil
addAction[232]={[1]='E'} --Debris Gambit
addAction[304]={[1]='C'} --C3PO Reb
addAction[311]={[1]='F',[2]='E'} --Lando Calrissian Reb
addAction[313]={[1]='TL'} --Magva Yarro
addAction[474]={[1]='E'} --Han Solo Res
addAction[327]={[1]='E'}--Millenium Falcon Reb (E)
addAction[472]={[1]='C'}--C-3PO Res (C)
addAction[616]={[1]='C'}--C-3PO Rep (C)
addAction[475]={[1]='TL'}--Rose Tico (TL)
addAction[331]={[1]='Piv'}--Pivot Wing (Pivot)
addAction[332]={[1]='Piv'}--Pivot Wing (Pivot)
addAction[333]={[1]='B'}--Servomotor (B)
addAction[334]={[1]='B'}--Servomotor (B)
addAction[251]={[1]='B',[2]='BR'}--Supernatural Reflexes (B,BR)
addAction[479]={[1]='BR'}--BB-8 (B,BR)
addAction[480]={[1]='BR'}--BB Astro (BR)
addAction[340]={[1]='TL'}--Krennic (TL)
addAction[486]={[1]='BR'}--Integrated S-Foils (BR)
addAction[487]={[1]='BR'}--Integrated S-Foils (BR)
addAction[345]={[1]='R'}--Minister Tua (Reinforce)
addAction[531]={[1]='C'}--Kraken(C)
addAction[352]={[1]='C'}-- 0-0-0 (C)
addAction[535]={[1]='Piv'}--Grappling Struts (Pivot)
addAction[555]={[1]='Piv'}--Grappling Struts (Pivot)
addAction[594]={[1]='Piv'}--Landing Struts(Pivot)
addAction[595]={[1]='Piv'}--Landing Struts(Pivot)
addAction[355]={[1]='B'}--Cad Bane (B)
addAction[357]={[1]='C'}--IG-88D (C)
addAction[542]={[1]='CL'}--Scimitar (CL)
addAction[286]={[1]='CL'}--Cloaking Device (CL)
addAction[551]={[1]='C'}--R4-P44 (C)
addAction[577]={[1]='C'}--Passive Sensors(C,TL)
addAction[376]={[1]='BR'}--Mist Hunter(BR)
addAction[582]={[1]='C'}--GA-97(C)
addAction[381]={[1]='F'}--Composure(F)
addAction[587]={[1]='C'}--PZ-4CO (C)
addAction[593]={[1]='R'}--Angled Deflectors (Reinforce)
addAction[704]={[1]='C'}--K-2SO (C)

--table referenced by upgrades that adds actions to all ships in a squad.
addSqdAction={}
addSqdAction[309]={[1]='E'} --Jyn Erso
addSqdAction[337]={[1]='Piv'}--Ciena Ree (Pivot)
addSqdAction[346]={[1]='B'}--Moff Jerjerrod (B)
addSqdAction[538]={[1]='F'}--Darth Sidious (F)
addSqdAction[554]={[1]='TL'}--Synchronized Console (TL)

-- FFG uses full name on factions, so a conversion is needed
ffgFaction = {}
ffgFaction[0] = 'Dum'
ffgFaction[1] = 'Zeo'
ffgFaction[2] = 'Fed'

cardBackDB = {}
cardBackDB['Dum'] = ''
cardBackDB['Zeo'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/Zeon%20Pilot%20Card%20Back.png'
cardBackDB['Fed'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/EFF%20Pilot%20Card%20Back.png'
cardBackDB['1'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Talent.png' --talent upgrades slot 1
cardBackDB['2'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Ballistic%20Weapon.png' --ballistic weapon upgrades slot 3
cardBackDB['3'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Beam%20Weapon.png' --beam weapon upgrades slot 4
cardBackDB['4'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Explosive%20Weapon.png' --explosive weapon upgrades slot 5
cardBackDB['5'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Melee%20Weapon.png' --melee weapon upgrades slot 6
cardBackDB['6'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Shield.png' --shield upgrades slot 7
cardBackDB['7'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Device.png' --device upgrades slot 8
cardBackDB['8'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Configuration.png' --configuration upgrades slot 9
cardBackDB['9'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Modification.png' --modification upgrades slot 10
cardBackDB['10'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Newtype.png' --newtype upgrades slot 11
cardBackDB['11'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Tactics.png' --tactics upgrades slot 12
cardBackDB['12'] = 'https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Backs/Upgrade%20Cards%20-%20Commander.png' --commander upgrades slot 13

-- Attempt on Unified Data Base, based on XWS (dropped after w1, too much hassle) and FFG conversion table
masterShipDB={}
masterShipDB[0]={['name']='',['Shield']=0,['size']='small',['agi']=1,['XWS']='',['Fac']={[0]=true},['arcs']={'front'}}
--starterMS
masterShipDB[1]={['name']='MS-06F Zaku II',['Shield']=1,['size']='small',['agi']=2,['XWS']='', ['Fac']={[1]=true}, ['arcs']={'front', 'melee'},
                            ['moveSet']={ 'rs4',
                                          'wbl3','ws3','wbr3',
                                          'wtl2','wbl2','bs2','wbr2','wtr2','rk2',
                                          'rtl1','bbl1','bs1','bbr1','rtr1','rfl1f','rfr1f','rs1r',
                                          'rs0'}}
--masterShipDB[2]={['name']='',['Shield']=0,['size']=0,['agi']=0,['XWS']='', ['Fac']={[0]=true}}
masterShipDB[3]={['name']='MS-06S Zaku II S-Type',['Shield']=1,['size']='small',['agi']=2,['XWS']='', ['Fac']={[1]=true}, ['arcs']={'front', 'melee'},
                            ['moveSet']={ 'ws4',
                                          'wtl3','wbl3','ws3','wbr3','wtr3','rk3',
                                          'wtl2','wbl2','bs2','wbr2','wtr2',
                                          'wtl1','bbl1','bs1','bbr1','wtr1','rfl1f','rfr1f','rs1r',
                                          'rs0'}}
masterShipDB[4]={['name']='MS-06R-1A Zaku II High Mobility Type',['Shield']=2,['size']='small',['agi']=2,['XWS']='', ['Fac']={[1]=true}, ['arcs']={'front', 'melee'},
                            ['moveSet']={ 'ws4',
                                          'wtl3','wbl3','ws3','wbr3','wtr3','rbl3s','rbr3s',
                                          'wtl2','bbl2','bs2','bbr2','wtr2',
                                          'rtl1','bbl1','bs1','bbr1','rtr1','rfl1f','rfr1f','rs1r',
                                          'rs0'}}
masterShipDB[5]={['name']='MS-09R Rick Dom',['Shield']=3,['size']='small',['agi']=2,['XWS']='', ['Fac']={[1]=true}, ['arcs']={'front', 'melee'},
                            ['moveSet']={ 'ws5','ws4',
                                          'rtl3','wbl3','bs3','wbr3','rtr3','rtl3t','rtr3t',
                                          'wtl2','bbl2','bs2','bbr2','wtr2',
                                          'wbl1','bs1','wbr1','rfl1f','rfr1f','rs1r',
                                          'rs0'}}
masterShipDB[6]={['name']='RGM-79 GM',['Shield']=1,['size']='small',['agi']=2,['XWS']='', ['Fac']={[2]=true}, ['arcs']={'front', 'melee'},
                            ['moveSet']={ 'rs4',
                                          'wbl3','ws3','wbr3','rk3',
                                          'wtl2','wbl2','bs2','wbr2','wtr2',
                                          'rtl1','bbl1','bs1','bbr1','rtr1','rfl1f','rfr1f','rs1r',
                                          'rs0'}}
masterShipDB[7]={['name']='RGC-80 GM Cannon',['Shield']=3,['size']='small',['agi']=1,['XWS']='', ['Fac']={[2]=true}, ['arcs']={'front', 'melee'},
                            ['moveSet']={ 'rbl3','ws3','rbr3',
                                          'wtl2','wbl2','bs2','wbr2','wtr2','rtl2t','rtr2t',
                                          'rtl1','bbl1','bs1','bbr1','rtr1','rfl1f','rfr1f','rs1r',
                                          'rs0'}}
masterShipDB[8]={['name']='RGM-79GS GM Command Space Type',['Shield']=3,['size']='small',['agi']=2,['XWS']='', ['Fac']={[2]=true}, ['arcs']={'front', 'melee'},
                            ['moveSet']={ 'ws4','rk4',
                                          'wtl3','wbl3','bs3','wbr3','wtr3',
                                          'wtl2','wbl2','bs2','wbr2','wtr2','wbr2','rbl2s','rbr2s',
                                          'btl1','bbl1','bbr1','btr1','rfl1f','rfr1f','rs1r',
                                          'rs0'}}
masterShipDB[9]={['name']='RX-77D Guncannon Mass Production Type',['Shield']=4,['size']='small',['agi']=1,['XWS']='', ['Fac']={[2]=true}, ['arcs']={'front', 'melee'},
                            ['moveSet']={ 'rs4',
                                          'rbl3','ws3','rbr3','wtl3t','wtr3t',
                                          'wtl2','wbl2','bs2','wbr2','wtr2',
                                          'rtl1','bbl1','bs1','bbr1','rtr1','rfl1f','rfr1f','rs1r',
                                          'rs0'}}

masterPilotDB={}
masterPilotDB[0]={['name']='',['Faction']= 0,['ship_type']=0,['cost']=0,['slot']={},['Shield']=0,['card']='',['cardB']='',['init']=0,['actSet']={}}
--MS-06F Zaku II Pilots
masterPilotDB[1]={['name']='Albert Bell',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=1,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Albert%20Bell%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[2]={['name']='Brennis Ox',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={1, 1, 2, 2, 3, 5, 6, 8, 10, 10},['Shield']=1,['init']=6,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Brennis%20Ox%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[3]={['name']='Capable Pilot',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=2,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Capable%20Pilot%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[4]={['name']='Charlotte Hepner',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=2,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Charlotte%20Hepner%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[5]={['name']='Christo Doerr',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=2,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Christo%20Doerr%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[6]={['name']='Crown',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['Force']=1,['init']=1,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Crown%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[7]={['name']='Denim',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=3,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Denim%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[8]={['name']='Eager Recruit',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=1,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Eager%20Recruit%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[9]={['name']='Gene',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=1,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Gene%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[10]={['name']='Gerald Sakai',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={1, 2, 2, 3, 5, 6, 8, 10},['Shield']=1,['init']=4,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Gerald%20Sakai%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[11]={['name']='Ian Graden',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={1, 2, 2, 3, 5, 6, 8},['Shield']=1,['init']=3,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Ian%20Graden%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[12]={['name']='Jake Guns',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=2,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Jake%20Guns%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[13]={['name']='J.Q.',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=1,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/J.Q.%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[14]={['name']='Karius Otto',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={1, 2, 2, 3, 5, 6, 8},['Shield']=1,['init']=3,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Karius%20Otto%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[15]={['name']='Kohm',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=1,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Kohm%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[16]={['name']='Lou Roher',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={1, 2, 2, 3, 5, 6, 8, 10},['Shield']=1,['init']=4,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Lou%20Roher%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[17]={['name']='Nikki Roberto',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=2,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Nikki%20Roberto%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[18]={['name']='Nimbus Schterzen',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={1, 2, 2, 3, 5, 6, 8, 10},['Shield']=1,['init']=4,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Nimbus%20Schterzen%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[19]={['name']='Robin Bradshaw',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=2,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Robin%20Bradshaw%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[20]={['name']='Shin Matsunaga',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={1, 1, 2, 2, 3, 5, 6, 8, 10, 10},['Shield']=1,['init']=6,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Shin%20Matsunaga%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[21]={['name']='Slender',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={2, 2, 3, 5, 6, 8},['Shield']=1,['init']=2,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Slender%20-%20MS-06F%20Zaku%20II.png'}
masterPilotDB[22]={['name']='Vincent Gleissner',['Faction']= 1,['ship_type']=1,['cost']=1,['slot']={1, 2, 2, 3, 5, 6, 8},['Shield']=1,['init']=3,{'F','E','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06F%20Zaku%20II/Vincent%20Gleissner%20-%20MS-06F%20Zaku%20II.png'}
--MS-06S Zaku II S-Type Pilots

masterPilotDB[23]={['name']='Char Aznable',['Faction']= 1,['ship_type']=3,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 5, 6, 7, 8, 10},['Shield']=1,['Force']=2,['init']=5,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06S%20Zaku%20II%20S-Type/Char%20Aznable%20-%20MS-06S%20Zaku%20II%20S-Type.png'}
masterPilotDB[24]={['name']='Doug Schneid',['Faction']= 1,['ship_type']=3,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 7, 8, 10},['Shield']=1,['init']=4,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06S%20Zaku%20II%20S-Type/Doug%20Schneid%20-%20MS-06S%20Zaku%20II%20S-Type.png'}
masterPilotDB[25]={['name']='Gabby Hazard',['Faction']= 1,['ship_type']=3,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 5, 6, 7, 8, 10},['Shield']=1,['init']=5,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06S%20Zaku%20II%20S-Type/Gabby%20Hazard%20-%20MS-06S%20Zaku%20II%20S-Type.png'}
masterPilotDB[26]={['name']='Johnny Ridden',['Faction']= 1,['ship_type']=3,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 5, 6, 7, 8, 10, 10},['Shield']=1,['init']=6,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06S%20Zaku%20II%20S-Type/Johnny%20Ridden%20-%20MS-06S%20Zaku%20II%20S-Type.png'}
masterPilotDB[27]={['name']='Ken Bederstadt',['Faction']= 1,['ship_type']=3,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 7, 8},['Shield']=1,['init']=3,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06S%20Zaku%20II%20S-Type/Ken%20Bederstadt%20-%20MS-06S%20Zaku%20II%20S-Type.png'}
masterPilotDB[28]={['name']='Nordit Bauer',['Faction']= 1,['ship_type']=3,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 5, 6, 7, 8, 10, 10},['Shield']=1,['init']=6,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06S%20Zaku%20II%20S-Type/Nordit%20Bauer%20-%20MS-06S%20Zaku%20II%20S-Type.png'}
masterPilotDB[29]={['name']='Resolute Squad Leader',['Faction']= 1,['ship_type']=3,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 7, 8},['Shield']=1,['init']=3,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06S%20Zaku%20II%20S-Type/Resolute%20Squad%20Leader%20-%20MS-06S%20Zaku%20II%20S-Type.png'}
masterPilotDB[30]={['name']='Robert Gilliam',['Faction']= 1,['ship_type']=3,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 5, 6, 7, 8, 10},['Shield']=1,['init']=5,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06S%20Zaku%20II%20S-Type/Robert%20Gilliam%20-%20MS-06S%20Zaku%20II%20S-Type.png'}
masterPilotDB[31]={['name']='Seasoned Commander',['Faction']= 1,['ship_type']=3,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 7, 8, 10},['Shield']=1,['init']=4,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06S%20Zaku%20II%20S-Type/Seasoned%20Commander%20-%20MS-06S%20Zaku%20II%20S-Type.png'}
--MS-06R-1A Zaku II High Mobility Type Pilots
masterPilotDB[32]={['name']='Anavel Gato',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 5, 6, 8, 10},['Shield']=2,['init']=5,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Anavel%20Gato%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[33]={['name']='Eric Manthfield',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 5, 6, 8, 10, 10},['Shield']=2,['init']=6,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Anavel%20Gato%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[34]={['name']='Gaia',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 8},['Shield']=2,['init']=3,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Gaia%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[35]={['name']='Hotshot Ace',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 8, 10},['Shield']=2,['init']=4,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Hotshot%20Ace%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[36]={['name']='Kamuji',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 8, 10},['Shield']=2,['Force']=1,['init']=4,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Kamuji%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[37]={['name']='Masaya Nakagawa',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 8, 10},['Shield']=2,['init']=4,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Masaya%20Nakagawa%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[38]={['name']='Mash',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 8},['Shield']=2,['init']=3,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Mash%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[39]={['name']='Nordit Bauer',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 5, 6, 8, 10, 10},['Shield']=2,['init']=6,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Nordit%20Bauer%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[40]={['name']='Ortega',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 8},['Shield']=2,['init']=3,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Ortega%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[41]={['name']='Reckless Test Pilot',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={2, 2, 2, 3, 5, 6, 8},['Shield']=2,['init']=2,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Reckless%20Test%20Pilot%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[42]={['name']='Robin Bradshaw',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={2, 2, 2, 3, 5, 6, 8},['Shield']=2,['init']=2,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Robin%20Bradshaw%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[43]={['name']='Shin Matsunaga',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 5, 6, 8, 10, 10},['Shield']=2,['init']=6,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Shin%20Matsunaga%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[44]={['name']='Siegfried Wedner',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 8, 10},['Shield']=2,['init']=4,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Siegfried%20Wedner%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[45]={['name']='Uma Lightning',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 5, 6, 8, 10},['Shield']=2,['init']=5,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Uma%20Lightning%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
masterPilotDB[46]={['name']='Vincent Gleissner',['Faction']= 1,['ship_type']=4,['cost']=1,['slot']={1, 2, 2, 2, 3, 5, 6, 8},['Shield']=2,['init']=3,['actSet']={'F','E','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type/Vincent%20Gleissner%20-%20MS-06R-1A%20Zaku%20II%20High%20Mobility%20Type.png'}
--MS-09R Rick Dom Pilots
masterPilotDB[47]={['name']='Anavel Gato',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={1, 1, 2, 2, 3, 4, 4, 5, 6, 10},['Shield']=3,['init']=5,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Anavel%20Gato%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[48]={['name']='Anxious Pilot',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={2, 2, 3, 4, 4, 5, 6},['Shield']=3,['init']=2,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Anxious%20Pilot%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[49]={['name']='Breniss Ox',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={1, 1, 2, 2, 3, 4, 4, 5, 6, 10, 10},['Shield']=3,['init']=6,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Breniss%20Ox%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[50]={['name']='Char Aznable',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={1, 1, 2, 2, 3, 4, 4, 5, 6, 10},['Shield']=3,['init']=5,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Char%20Aznable%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[51]={['name']='Ein Lewi',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={2, 2, 3, 4, 4, 5, 6},['Shield']=3,['init']=1,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Ein%20Lewi%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[52]={['name']='Gaius Zemela',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={1, 2, 2, 3, 4, 4, 5, 6},['Shield']=3,['init']=3,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Gaius%20Zemela%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[53]={['name']='Gerald Sakai',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={1, 2, 2, 3, 4, 4, 5, 6, 10},['Shield']=3,['init']=4,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Gerald%20Sakai%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[54]={['name']='Gusta Piper',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={2, 2, 3, 4, 4, 5, 6},['Shield']=3,['init']=2,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Gusta%20Piper%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[55]={['name']='Huyman Carlyle',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={1, 2, 2, 3, 4, 4, 5, 6},['Shield']=3,['init']=3,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Huyman%20Carlyle%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[56]={['name']='Kelley Layzner',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={2, 2, 3, 4, 4, 5, 6},['Shield']=3,['init']=2,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Kelley%20Layzner%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[57]={['name']='Lilia Flaubert',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={2, 2, 3, 4, 4, 5, 6},['Shield']=3,['init']=2,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Lilia%20Flaubert%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[58]={['name']='Reliable Wingman',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={1, 2, 2, 3, 4, 4, 5, 6},['Shield']=3,['init']=3,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Reliable%20Wingman%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[59]={['name']='Serein Experi',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={1, 2, 2, 3, 4, 4, 5, 6, 10},['Shield']=3,['init']=4,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Serein%20Experi%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[60]={['name']='Sophie Fran',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={1, 2, 2, 3, 4, 4, 5, 6, 10},['Shield']=3,['init']=4,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Sophie%20Fran%20-%20MS-09R%20Rick%20Dom.png'}
masterPilotDB[61]={['name']='Vanessa Vermilion',['Faction']= 1,['ship_type']=5,['cost']=1,['slot']={1, 2, 2, 3, 4, 4, 5, 6},['Shield']=3,['init']=3,['actSet']={'F','L','B','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/Zeon/MS-09R%20Rick%20Dom/Vanessa%20Vermilion%20-%20MS-09R%20Rick%20Dom.png'}
--RGM-79 GM
masterPilotDB[62]={['name']='Adam Stingray',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 10},['Shield']=2,['init']=4,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Adam%20Stingray%20-%20RGM-79%20GM.png'}
masterPilotDB[63]={['name']='Allain Aylward',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=2,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Allain%20Aylward%20-%20RGM-79%20GM.png'}
masterPilotDB[64]={['name']='Anish Lofman',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=3,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Anish%20Lofman%20-%20RGM-79%20GM.png'}
masterPilotDB[65]={['name']='Charles Kissingham',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 3, 3, 4, 5, 6, 7, 10, 10},['Shield']=2,['Charge']=1,['init']=6,
                  ['actSet']={'F','TL','B'},['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Charles%20Kissingham%20-%20RGM-79%20GM.png'}
masterPilotDB[66]={['name']='Dennis Burrow',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=2,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Dennis%20Burrow%20-%20RGM-79%20GM.png'}
masterPilotDB[67]={['name']='Earnest Cadet',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=1,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Earnest%20Cadet%20-%20RGM-79%20GM.png'}
masterPilotDB[68]={['name']='Fred Reber',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=3,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Fred%20Reber%20-%20RGM-79%20GM.png'}
masterPilotDB[69]={['name']='Jack Bayard',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=2,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Jack%20Bayard%20-%20RGM-79%20GM.png'}
masterPilotDB[70]={['name']='Jean Dibebie',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=3,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Jean%20Dibebie%20-%20RGM-79%20GM.png'}
masterPilotDB[71]={['name']='Kamuna Tachibana',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=3,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Kamuna%20Tachibana%20-%20RGM-79%20GM.png'}
masterPilotDB[72]={['name']='Leung Lee-Fai',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=2,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Leung%20Lee-Fai%20-%20RGM-79%20GM.png'}
masterPilotDB[73]={['name']='Lil Sommers',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=1,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Lil%20Sommers%20-%20RGM-79%20GM.png'}
masterPilotDB[74]={['name']='Master Pierce Rayer',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 10},['Shield']=2,['init']=5,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Master%20Pierce%20Rayer%20-%20RGM-79%20GM.png'}
masterPilotDB[75]={['name']='Maximilian Berger',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=3,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Maximilian%20Berger%20-%20RGM-79%20GM.png'}
masterPilotDB[76]={['name']='Philip Hughes',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=3,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Philip%20Hughes%20-%20RGM-79%20GM.png'}
masterPilotDB[77]={['name']='Proficient Pilot',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=2,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Proficient%20Pilot%20-%20RGM-79%20GM.png'}
masterPilotDB[78]={['name']='Summona Fulis',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=2,['init']=1,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Summona%20Fulis%20-%20RGM-79%20GM.png'}
masterPilotDB[79]={['name']='Tenneth A. Jung',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 10, 10},['Shield']=2,['init']=6,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Tenneth%20A.%20Jung%20-%20RGM-79%20GM.png'}
masterPilotDB[80]={['name']='Travis Kirkland',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 10},['Shield']=2,['init']=4,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Travis%20Kirkland%20-%20RGM-79%20GM.png'}
masterPilotDB[81]={['name']='Yuji Arcana',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 10},['Shield']=2,['init']=4,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Yuji%20Arcana%20-%20RGM-79%20GM.png'}
masterPilotDB[82]={['name']='Yuu Kajima',['Faction']= 2,['ship_type']=6,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 10},['Shield']=2,['init']=5,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79%20GM/Yuu%20Kajima%20-%20RGM-79%20GM.png'}
--RGC-80 GM Cannon Pilots
masterPilotDB[83]={['name']='Allain Aylward',['Faction']= 2,['ship_type']=7,['cost']=1,['slot']={2, 2, 3, 3, 4, 5, 7},['Shield']=3,['init']=2,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGC-80%20GM%20Cannon/Allain%20Aylward%20-%20RGC-80%20GM%20Cannon.png'}
masterPilotDB[84]={['name']='Chap Adel',['Faction']= 2,['ship_type']=7,['cost']=1,['slot']={2, 2, 3, 3, 4, 5, 7},['Shield']=3,['init']=2,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGC-80%20GM%20Cannon/Chap%20Adel%20%20-%20RGC-80%20GM%20Cannon.png'}
masterPilotDB[85]={['name']='Dennis Burrow',['Faction']= 2,['ship_type']=7,['cost']=1,['slot']={2, 2, 3, 3, 4, 5, 7},['Shield']=3,['init']=2,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGC-80%20GM%20Cannon/Dennis%20Burrow%20-%20RGC-80%20GM%20Cannon.png'}
masterPilotDB[86]={['name']='Leung Lee-Fai',['Faction']= 2,['ship_type']=7,['cost']=1,['slot']={2, 2, 3, 3, 4, 5, 7},['Shield']=3,['init']=2,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGC-80%20GM%20Cannon/Leung%20Lee-Fai%20-%20RGC-80%20GM%20Cannon.png'}
masterPilotDB[87]={['name']='Lil Sommers',['Faction']= 2,['ship_type']=7,['cost']=1,['slot']={2, 2, 3, 3, 4, 5, 7},['Shield']=3,['init']=1,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGC-80%20GM%20Cannon/Lil%20Sommers%20-%20RGC-80%20GM%20Cannon.png'}
masterPilotDB[88]={['name']='Lydo Wolf',['Faction']= 2,['ship_type']=7,['cost']=1,['slot']={1, 1, 2, 2, 3, 3, 4, 5, 7, 10, 10},['Shield']=3,['init']=6,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGC-80%20GM%20Cannon/Lydo%20Wolf%20-%20RGC-80%20GM%20Cannon.png'}
masterPilotDB[89]={['name']='Master Pierce Rayer',['Faction']= 2,['ship_type']=7,['cost']=1,['slot']={1, 1, 2, 2, 3, 3, 4, 5, 7, 10},['Shield']=3,['init']=5,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGC-80%20GM%20Cannon/Master%20Pierce%20Rayer%20-%20RGC-80%20GM%20Cannon.png'}
masterPilotDB[90]={['name']='Maximilian Berger',['Faction']= 2,['ship_type']=7,['cost']=1,['slot']={1, 2, 2, 3, 3, 4, 5, 7},['Shield']=3,['init']=3,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGC-80%20GM%20Cannon/Maximilian%20Berger%20-%20RGC-80%20GM%20Cannon.png'}
masterPilotDB[91]={['name']='Restless Rookie',['Faction']= 2,['ship_type']=7,['cost']=1,['slot']={2, 2, 3, 3, 4, 5, 7},['Shield']=3,['init']=1,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGC-80%20GM%20Cannon/Restless%20Rookie%20-%20RGC-80%20GM%20Cannon.png'}
masterPilotDB[92]={['name']='Skillful Gunner',['Faction']= 2,['ship_type']=7,['cost']=1,['slot']={1, 2, 2, 3, 3, 4, 5, 7},['Shield']=3,['init']=3,['actSet']={'F','TL','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGC-80%20GM%20Cannon/Skillful%20Gunner%20-%20RGC-80%20GM%20Cannon.png'}
--RGM-79GS GM Command Space Type Pilots
masterPilotDB[93]={['name']='Alpha A. Bate',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=3,['init']=3,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Alpha%20A.%20Bate%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[94]={['name']='Bernard Monsha',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=3,['init']=3,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Bernard%20Monsha%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[95]={['name']='Chap Adel',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=3,['init']=2,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Chap%20Adel%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[96]={['name']='Cherie Allison',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=3,['init']=3,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Cherie%20Allison%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[97]={['name']='Formidable Veteran',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=3,['init']=3,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Formidable%20Veteran%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[98]={['name']='Hugues Courand',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 10},['Shield']=3,['init']=4,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Hugues%20Courand%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[99]={['name']='Jaime Carmona',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=3,['init']=3,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Jaime%20Carmona%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[100]={['name']='Kamal Kumar',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=3,['init']=2,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Kamal%20Kumar%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[101]={['name']='Mark Bell',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7},['Shield']=3,['init']=3,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Mark%20Bell%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[102]={['name']='Renowed Ace',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 10},['Shield']=3,['init']=4,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Renowed%20Ace%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[103]={['name']='Tenneth A. Jung',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 10, 10},['Shield']=3,['init']=6,
                  ['actSet']={'F','TL','BR','B'},['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Tenneth%20A.%20Jung%20-%20RGM-79GS%20GM%20Command.png'}
masterPilotDB[104]={['name']='Yuu Kajima',['Faction']= 2,['ship_type']=8,['cost']=1,['slot']={1, 1, 2, 2, 2, 3, 3, 4, 5, 6, 7, 10},['Shield']=3,['init']=5,['actSet']={'F','TL','BR','B'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RGM-79GS%20GM%20Command/Yuu%20Kajima%20-%20RGM-79GS%20GM%20Command.png'}
--RX-77D Guncannon Mass Production Type Pilots

masterPilotDB[105]={['name']='Hotshot Ace',['Faction']= 2,['ship_type']=9,['cost']=1,['slot']={1, 2, 2, 3, 3, 3, 5, 7, 10},['Shield']=3,['init']=4,['actSet']={'F','TL','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RX-77D%20Guncannon%20MP%20Type/Hotshot%20Ace%20-%20RX-77D%20Guncannon%20MP%20Type.png'}
masterPilotDB[106]={['name']='Jean Dibebie',['Faction']= 2,['ship_type']=9,['cost']=1,['slot']={1, 2, 2, 3, 3, 3, 5, 7},['Shield']=3,['init']=3,['actSet']={'F','TL','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RX-77D%20Guncannon%20MP%20Type/Jean%20Dibebie%20-%20RX-77D%20Guncannon%20MP%20Type.png'}
masterPilotDB[107]={['name']='Lieutenant Agar',['Faction']= 2,['ship_type']=9,['cost']=1,['slot']={1, 2, 2, 3, 3, 3, 5, 7},['Shield']=3,['init']=2,['actSet']={'F','TL','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RX-77D%20Guncannon%20MP%20Type/Lieutenant%20Agar%20-%20RX-77D%20Guncannon%20MP%20Type.png'}
masterPilotDB[108]={['name']='Lydo Wolf',['Faction']= 2,['ship_type']=9,['cost']=1,['slot']={1, 1, 2, 2, 3, 3, 3, 5, 7, 10, 10},['Shield']=3,['init']=6,['actSet']={'F','TL','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RX-77D%20Guncannon%20MP%20Type/Lydo%20Wolf%20-%20RX-77D%20Guncannon%20MP%20Type.png'}
masterPilotDB[109]={['name']='Master Pierce Rayer',['Faction']= 2,['ship_type']=9,['cost']=1,['slot']={1, 1, 2, 2, 3, 3, 3, 5, 7, 10},['Shield']=3,['init']=5,['actSet']={'F','TL','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RX-77D%20Guncannon%20MP%20Type/Master%20Pierce%20Rayer%20-%20RX-77D%20Guncannon%20MP%20Type.png'}
masterPilotDB[110]={['name']='Maximilian Berger',['Faction']= 2,['ship_type']=9,['cost']=1,['slot']={1, 2, 2, 3, 3, 3, 5, 7},['Shield']=3,['init']=3,['actSet']={'F','TL','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RX-77D%20Guncannon%20MP%20Type/Maximilian%20Berger%20-%20RX-77D%20Guncannon%20MP%20Type.png'}
masterPilotDB[111]={['name']='Skilled Pilot',['Faction']= 2,['ship_type']=9,['cost']=1,['slot']={2, 2, 3, 3, 3, 5, 7},['Shield']=3,['init']=2,['actSet']={'F','TL','BR'},
                  ['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/unit%20cards/EFF/RX-77D%20Guncannon%20MP%20Type/Skilled%20Pilot%20-%20RX-77D%20Guncannon%20MP%20Type.png'}

--talent upgrades slot 1
--handheld weapon upgrades slot 2 ['slot']=3,['remSlot']={2},
--ballistic weapon upgrades slot 3
--beam weapon upgrades slot 4
--explosive weapon upgrades slot 5
--melee weapon upgrades slot 6
--shield upgrades slot 7
--device upgrades slot 8
--configuration upgrades slot 9
--modification upgrades slot 10
--newtype upgrades slot 11
--tactics upgrades slot 12
--commander upgrades slot 13

masterUpgradesDB={}

masterUpgradesDB[230]={['name']='100mm Machine Gun',['slot']=3,['remSlot']={2},['cost']=1,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Ballistic%20Weapons/100mm%20Machine%20Gun.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[231]={['name']='Bullpup Machine Gun',['slot']=3,['remSlot']={2},['cost']=1,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Ballistic%20Weapons/Bullpup%20Machine%20Gun.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[232]={['name']='Zaku Machine Gun',['slot']=3,['remSlot']={2},['cost']=1,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Ballistic%20Weapons/Zaku%20Machine%20Gun.png',['restriction']={['Faction']={[1]=true}}}
masterUpgradesDB[233]={['name']='Head-Mounted Vulcan Gun',['slot']=3,['cost']=1,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Ballistic%20Weapons/Zaku%20Machine%20Gun.png',['restriction']={['Faction']={[1]=true}}}
masterUpgradesDB[234]={['name']='Beam Spray Gun',['slot']=4,['remSlot']={2},['cost']=2,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Beam%20Weapons/Beam%20Spray%20Gun.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[235]={['name']='Beam Gun',['slot']=4,['remSlot']={2},['cost']=2,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Beam%20Weapons/Beam%20Spray%20Gun.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[236]={['name']='Scattering Beam Gun',['slot']=4,['cost']=2,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Beam%20Weapons/Beam%20Spray%20Gun.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[237]={['name']='Beam Bazooka',['slot']=4,['remSlot']={2},['cost']=2,['Charge']=4,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Beam%20Weapons/Beam%20Spray%20Gun.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[238]={['name']='Cracker Grenade',['slot']=8,['cost']=2,['Charge']=2,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Devices/Cracker%20Grenade.png',['restriction']={['Faction']={[1]=true}}}
masterUpgradesDB[239]={['name']='240mm Cannon',['slot']=5,['cost']=2,['Charge']=3,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Explosive%20Weapons/240mm%20Cannon.png',['restriction']={['Faction']={[2]=true},['ship']={7}, ['Size']=nil}}
masterUpgradesDB[240]={['name']='280mm Zaku Bazooka',['slot']=5,['remSlot']={2},['cost']=2,['Charge']=3,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Explosive%20Weapons/280mm%20Zaku%20Bazooka.png',['restriction']={ ['Size']={[1]=true,[2]=true}}}
masterUpgradesDB[241]={['name']='3-tube Missile Pod',['slot']=5,['cost']=2,['Charge']=5,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Explosive%20Weapons/3-tube%20Missile%20Pod.png',['restriction']={['Faction']={[1]=true},['ship']={1}, ['Size']=nil}}
masterUpgradesDB[242]={['name']='Simplified Missile Launcher',['slot']=5,['remSlot']={2},['cost']=2,['Charge']=5,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Explosive%20Weapons/3-tube%20Missile%20Pod.png',['restriction']={['Faction']={[1]=true},['ship']={1}, ['Size']=nil}}
masterUpgradesDB[243]={['name']='380mm Hyper Bazooka',['slot']=5,['remSlot']={2},['cost']=2,['Charge']=3,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Explosive%20Weapons/380mm%20Hyper%20Bazooka.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[244]={['name']='360mm Giant Bazooka',['slot']=5,['remSlot']={2},['cost']=2,['Charge']=2,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Explosive%20Weapons/380mm%20Hyper%20Bazooka.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[245]={['name']='Beam Saber',['slot']=6,['remSlot']={2},['cost']=2,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Melee%20Weapons/Beam%20Saber.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[246]={['name']='Double Beam Saber',['slot']=6,['remSlot']={2, 2, 6},['cost']=2,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Melee%20Weapons/Beam%20Saber.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[247]={['name']='Heat Hawk',['slot']=6,['remSlot']={2},['cost']=1,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Melee%20Weapons/Heat%20Hawk.png',['restriction']={['Faction']={[1]=true}}}
masterUpgradesDB[248]={['name']='Double Heat Hawk',['slot']=6,['remSlot']={2, 2, 6},['cost']=1,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Melee%20Weapons/Heat%20Hawk.png',['restriction']={['Faction']={[1]=true}}}
masterUpgradesDB[249]={['name']='Large Shield',['slot']=7,['remSlot']={2},['cost']=2,['Charge']=1,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Shields/Large%20Shield.png',['restriction']={['Faction']={[2]=true}}}
masterUpgradesDB[250]={['name']='Knuckle Shield',['slot']=7,['remSlot']={2},['cost']=1,['Charge']=1,['card']='https://raw.githubusercontent.com/WizardofAZ9/TTS_MSG-Flightpath/master/msg_assets/upgrade%20cards/Shields/Zaku%20Shield.png',['restriction']={['Faction']={[1]=true}}}
masterUpgradesDB[251]={['name']='Strengthened Frame',['slot']=10,['cost']='a',['card']='http://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_73.png',['restriction']={ }}
masterUpgradesDB[252]={['name']='Shield Upgrade',['slot']=10,['cost']='a',['shd']=1,['card']='http://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_75.png',['restriction']={ }}

ffgSpecial = {}
ffgSpecial[315]= 'Crew'--r2d2crew
ffgSpecial[324]= 'Astr'--r2d2astro
ffgSpecial[321]= 'Rebel Gunner'--hanReb
ffgSpecial[389]= 'Scum Gunner'--hanScu
ffgSpecial[474]= 'Resist. Crew'--Han Res
ffgSpecial[311]= 'Rebel Crew'--landoReb
ffgSpecial[385]= 'Scum Crew' --landoScu
ffgSpecial[306]= 'Rebel Crew' --chewReb
ffgSpecial[382]= 'Scum Crew' --chewScu
ffgSpecial[473]= 'Resist. Crew' --chewRes
ffgSpecial[472]= 'Resist. Crew'--3po Res
ffgSpecial[304]= 'Rebel Crew' --3po Reb


-- on load initiate the process
function onLoad()
    initiate()
end

-- Initial function: Creates a start button for each mode: FFG Spawner (paste the link of the squad in the FFG web site and spawn), TTS Spawner (write or paste a snippet and spawn) and List Builder (offers options to build a squadron on the fly)
function initiate()
    self.clearButtons()
    self.clearInputs()
    self.createButton({click_function = 'singleSpawner', function_owner = self, label = 'Single Spawner', position = {0,0.45,-0.2}, width = 1600, height = 380, font_size = 200, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'spawnerStart', function_owner = self, label = 'TTS Spawner', position = {0,0.45,0.4}, width = 1600, height = 380, font_size = 250, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'builderStart', function_owner = self, label = 'Builder', position = {0,0.45,0.7}, width = 1600, height = 380, font_size = 250, scale = {0.25,0.25,0.25}})
end

function DummyFFG()
end

--TTS spawner input field
function action(obj, playerColor, value, editing)
    if not editing then
        lista = value
    else
        nl_index = string.find(value, '\n')
        if nl_index != nil then
            lista = string.sub(value, 1,nl_index-1)
            validCheck()
        end
    end
end

-- Single Spawner input field
function action3(obj, playerColor, value, editing)
    if not editing then
        single = value
    else
        nl_index = string.find(value, '\n')
        if nl_index != nil then
            single = string.sub(value, 1,nl_index-1)
            singleSearch()
        end
    end
end

-- Single Spawner: Receives a string, then goes across all card names and spawns that card with its appropriate components.
function singleSpawner()
    self.clearInputs()
    self.clearButtons()
    self.createButton({click_function = 'DummyFFG', function_owner = self, label = 'Type a card name', position = {0,0.45,-0.37}, width = 1800, height = 280, font_size = 200,  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'singleSearch', function_owner = self, label = 'Search', position = {0.45,0.45,-0.17}, width = 1200, height = 320, font_size = 200,  scale = {0.15,0.15,0.15}})
    self.createInput({input_function = 'action3', function_owner = self, position = {-0.3,0.45,-0.17}, width = 1800, height = 200, font_size = 160, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'initiate', function_owner = self, label = 'Back', position = {0.7,0.45,0.8}, width = 1000, height = 300, font_size = 150,  scale = {0.21,0.21,0.21}})
    self.createButton({click_function = 'DummyFFG', function_owner = self, label = 'Pilots', position = {-0.45,0.45,-0.025}, width = 1000, height = 280, font_size = 200,  scale = {0.20,0.20,0.20}})
    self.createButton({click_function = 'DummyFFG', function_owner = self, label = 'Upgrades', position = {0.45,0.45,-0.025}, width = 1000, height = 280, font_size = 200,  scale = {0.20,0.20,0.20}})
end

function singleSearch()
    self.clearButtons()
    self.clearInputs()
    singleSpawner()
    butPilCount = 0
    butPilData = {}
    butUpCount = 0
    butUpData = {}
    if single ~= nil then
        for k, v in pairs(masterPilotDB) do
            if string.find(string.lower(v['name']), string.lower(single), 1, true) then
                if butPilCount < 7 then
                    butPilCount = butPilCount + 1
                    self.createButton({click_function = 'singlePil'..butPilCount, function_owner = self, label = v['name']..' ('..masterShipDB[v['ship_type']]['name']..')', position = {-0.45,0.45,0+butPilCount*0.09}, width = 2800, height = 230, font_size = 120,  scale = {0.15,0.15,0.15}})
                    butPilData[butPilCount] = k
                end
            end
        end
        for k, v in pairs(masterUpgradesDB) do
            if string.find(string.lower(v['name']), string.lower(single), 1, true) then
                if butUpCount < 7 then
                    butUpCount = butUpCount+1
                    local upName = v['name']
                    if ffgSpecial[k] ~= nil then
                        upName = upName..' ('..ffgSpecial[k]..')'
                    end
                    butUpData[butUpCount] = k
                    self.createButton({click_function = 'singleUp'..butUpCount, function_owner = self, label = upName, position = {0.45,0.45,0+butUpCount*0.09}, width = 2800, height = 230, font_size = 120,  scale = {0.15,0.15,0.15}})
                end
            end
        end
    else
        print('Please type a card name')
    end
    single = nil
end

function singlePil1()
    local pilotPick = butPilData[1]
    singlePilotSpawn(pilotPick)
end
function singlePil2()
    local pilotPick = butPilData[2]
    singlePilotSpawn(pilotPick)
end
function singlePil3()
    local pilotPick = butPilData[3]
    singlePilotSpawn(pilotPick)
end
function singlePil4()
    local pilotPick = butPilData[4]
    singlePilotSpawn(pilotPick)
end
function singlePil5()
    local pilotPick = butPilData[5]
    singlePilotSpawn(pilotPick)
end
function singlePil6()
    local pilotPick = butPilData[6]
    singlePilotSpawn(pilotPick)
end
function singlePil7()
    local pilotPick = butPilData[7]
    singlePilotSpawn(pilotPick)
end

function singleUp1()
    local upPick = butUpData[1]
    singleUpSpawn(upPick)
end
function singleUp2()
    local upPick = butUpData[2]
    singleUpSpawn(upPick)
end
function singleUp3()
    local upPick = butUpData[3]
    singleUpSpawn(upPick)
end
function singleUp4()
    local upPick = butUpData[4]
    singleUpSpawn(upPick)
end
function singleUp5()
    local upPick = butUpData[5]
    singleUpSpawn(upPick)
end
function singleUp6()
    local upPick = butUpData[6]
    singleUpSpawn(upPick)
end
function singleUp7()
    local upPick = butUpData[7]
    singleUpSpawn(upPick)
end


function singlePilotSpawn(Id)
    partList={}
    partList.spawnCard = self
    partList.Pilots = {}
    partList.Pilots[1] = Id
    partList.Upgrades = {}
    partList.Upgrades[1] = {}
    partList.Faction = masterPilotDB[Id]['Faction']
    idSpawner(partList)
    singleSpawner()
end

function singleUpSpawn(upId)
    partList={}
    partList.spawnCard = self
    partList.Pilots = {}
    partList.Pilots[1] = 0
    partList.Upgrades = {}
    partList.Upgrades[1] = {}
    partList.Upgrades[1][1] = upId
    partList.Faction = ffgFaction[0]
    idSpawner(partList)
    singleSpawner()
end

--[[
    id table should look like this:
    idTable.Pilots = {[1]=id1, [2]=id2}
    idTable.Upgrades = {[1] = {[1]=upId1, [2]=upId2},
                        [2]={[1]=upId3, [2]=upId3}}
    idTable.Faction = masterPilotDB[id1]['Faction']
]]

dialSkin={
  [1]='http://cloud-3.steamusercontent.com/ugc/776248816759536085/F1682EB306C8FDFA5A1D2AD7FE41691532156412/',
  [2]='http://cloud-3.steamusercontent.com/ugc/776248816759536533/909FE80347105F36346550CDA6246082AA0729A6/',}

function idSpawner(idTable)
    fList={}
    fList.Pilots = {}
    fList.Upgrades = {}
    if idTable.Faction == nil then
        fList.Faction = masterPilotDB[idTable.Pilots[1]]['Faction']
    else
        fList.Faction = idTable.Faction
    end
    fList.factionDial=dialSkin[fList.Faction]
    fList.sqdAction = {}
    for k,v in pairs (idTable.Pilots) do
        local name = masterPilotDB[v]['name']
        fList.Pilots[k] ={}
        fList.Pilots[k]['id'] = v
        fList.Pilots[k]['name'] = name
        fList.Pilots[k]['card'] = masterPilotDB[v]['card']
        fList.Pilots[k]['cardB'] = cardBackDB[ffgFaction[fList.Faction]]
        local Ship = masterPilotDB[v]['ship_type']
        fList.Pilots[k]['Ship'] = Ship
        fList.Pilots[k]['Size'] = masterShipDB[Ship]['size']
        fList.Pilots[k]['Shield'] = masterShipDB[Ship]['Shield']
        fList.Pilots[k]['bombD'] = 's1'
        fList.Pilots[k]['Docking'] = masterShipDB[Ship]['Docking']
        fList.Pilots[k]['Data'] = {}
        fList.Pilots[k]['Data']['moveSet'] = masterShipDB[Ship]['moveSet']
        fList.Pilots[k]['Data']['arcs'] = masterShipDB[Ship]['arcs']
        fList.Pilots[k]['Data']['actSet'] = masterPilotDB[v]['actSet']
        fList.Pilots[k]['Data']['Faction'] = fList.Faction
        fList.Pilots[k]['Data']['Size'] = fList.Pilots[k]['Size']
        if v == 150 then  -- Emon Azzameen special drops
            fList.Pilots[k]['bombD'] = fList.Pilots[k]['bombD'] .. ':s3:tr3:te3'
        elseif v == 205 then  -- Sol Sixxa special drops
            fList.Pilots[k]['bombD'] = fList.Pilots[k]['bombD'] .. ':te1:tr1'
        elseif Ship == 19 then -- TIE Bomber special drops
            fList.Pilots[k]['bombD'] = fList.Pilots[k]['bombD'] .. ':be1:br1'
        end

        if masterShipDB[Ship]['sTurret'] ~= nil then
            fList.Pilots[k]['Turret'] = 1
        elseif masterShipDB[Ship]['dTurret'] ~= nil then
            fList.Pilots[k]['Turret'] = 2
        end
        id = v
        if masterPilotDB[id]['Condition'] ~= nil then
            fList.Pilots[k]['Condition'] = masterPilotDB[id]['Condition']
        end
        if masterPilotDB[id]['Charge'] ~= nil then
            fList.Pilots[k]['Charge'] = masterPilotDB[id]['Charge']
        else
            fList.Pilots[k]['Charge'] = 0
        end
        if masterPilotDB[id]['Force'] ~= nil then
            fList.Pilots[k]['Force'] = masterPilotDB[id]['Force']
        else
            fList.Pilots[k]['Force'] = 0
        end
        fList.Upgrades[k] = {}
        local skilled_bombardier = false
        for key,value in pairs (idTable.Upgrades[k]) do
            local name = masterUpgradesDB[value]['name']
            local upSlot = masterUpgradesDB[value]['slot']
            fList.Upgrades[k][key] = {}
            fList.Upgrades[k][key]['name'] = name
            fList.Upgrades[k][key]['card'] = masterUpgradesDB[value]['card']
            for a,b in pairs(addAction) do --Upgrades that adds an action to a ship
                if a == value then
                    for K,V in pairs(b) do
                        table.insert(fList.Pilots[k]['Data']['actSet'],V)
                    end
                end
            end
            for a,b in pairs(addSqdAction) do --upgrades that adds an action to the whole squad, sets up a list of actions that will be added later
                if a == value then
                    for K,V in pairs(b) do
                        table.insert(fList.sqdAction,V)
                    end
                end
            end
            if masterUpgradesDB[value]['cardB'] ==  nil then
                fList.Upgrades[k][key]['cardB'] = cardBackDB[tostring(upSlot)]
            else
                fList.Upgrades[k][key]['cardB'] = masterUpgradesDB[value]['cardB']
            end
            if masterUpgradesDB[value]['Charge'] ~= nil then
                fList.Upgrades[k][key]['Charge'] = masterUpgradesDB[value]['Charge']
            else
                fList.Upgrades[k][key]['Charge'] = 0
            end
            if fList.Pilots[k]['Turret'] == nil then
                if masterUpgradesDB[value]['sTurret']  then
                    fList.Pilots[k]['Turret'] = 1
                    if fList.Pilots[k]['Data']['arcs'] == nil then
                        fList.Pilots[k]['Data']['arcs'] = {'singleturret'}
                    else
                        table.insert(fList.Pilots[k]['Data']['arcs'], 'singleturret')
                    end
                end
            end
            if masterUpgradesDB[value]['Force'] ~= nil then
                fList.Pilots[k]['Force'] = fList.Pilots[k]['Force'] + masterUpgradesDB[value]['Force']
            end
            if masterUpgradesDB[value]['shd'] ~= nil then
                fList.Pilots[k]['Shield'] = fList.Pilots[k]['Shield'] + masterUpgradesDB[value]['shd']
            end
            if masterUpgradesDB[value]['Condition'] ~= nil then
                fList.Upgrades[k][key]['Condition'] = masterUpgradesDB[value]['Condition']
            else
                fList.Upgrades[k][key]['Condition'] = false
            end
            if upSlot == 12 then
                fList.Pilots[k]['Bomb']= true
                if name == 'DRK-1 Probe Droids' then
                    fList.Pilots[k]['Bomb']= false
                end
            elseif upSlot == 18 then
                fList.Upgrades[k][key]['Config'] = true
            end
            if masterUpgradesDB[value].Docking ~= nil then
                fList.Pilots[k].Docking = masterUpgradesDB[value].Docking
            end
            if value == 279 then  -- Skilled Bombardier special drops
                skilled_bombardier = true
                --fList.Pilots[k]['bombD'] = fList.Pilots[k]['bombD'] ..  ':s2:tr2:te2:be2:br2'
            elseif value == 255 then  -- Trajectory Simulator special drop
                fList.Pilots[k]['bombD'] = fList.Pilots[k]['bombD'] ..  ':s5r'
            end
        end
        if skilled_bombardier then
            local bombD = fList.Pilots[k]['bombD']
            parts = mysplit(bombD,':')
            for k, part in pairs(parts) do
                pre, speedstr, post = string.match(part, "(%a+)(%d)(%a*)")
                speed = tonumber(speedstr)
                if speed > 1 then
                    bombD = bombD .. ":" .. pre .. tostring(speed - 1) ..  post
                end
                if (pre == 's' and (speed < 5)) or (speed < 3) then
                    bombD = bombD .. ":" .. pre .. tostring(speed + 1) ..  post
                end
            end
            fList.Pilots[k]['bombD'] = bombD
        end

    end
    for k,v in pairs(fList.sqdAction) do -- adds Squad actions coming from specific upgrades
        for K,V in pairs(fList.Pilots) do
            table.insert(V['Data']['actSet'],v)
        end
    end
    if savingList == true then
        saveToDisk(fList)
    else
        fList.spawnCard = self
        spawnNow(fList)
    end
end

cardLua = [[
self.createButton({
  click_function = 'spawnerCaller',
  function_owner = self,
  label          = 'Spawn',
  position       = {0,0.02,0.35},
  rotation       = {0,0,0},
  scale          = {0.1,0.1,0.1},
  width          = 2000,
  height         = 500,
  font_size      = 400,
  color          = 'Black',
  font_color     = 'White',
  tooltip        = 'Click here to spawn the saved list',
})

function spawnerCaller()
    spawnTable = self.getTable("List")
    spawnTable.spawnCard = self
    Global.call('newSpawner', spawnTable)
    spawnTable = nil
end

function onSave()
    if state == nil then
        local state = {cardData=self.getTable("List")}
        return JSON.encode(state)
    end
end

-- Restore self state
function onLoad(savedData)
    --print("OnLoad: ".. self.getName() .. " " .. savedData)
    if savedData ~= "" then
        self.setTable("List", JSON.decode(savedData).cardData)
    end
end
]]

function saveToDisk(finalList)
    print('Saving to Disk')
    local accBag = getObjectFromGUID('53ad3d')-- Accessories bag
    local accList = accBag.getObjects()
    for k, v in pairs(accBag.getObjects()) do
        if v.name == 'Data Card' then
            dataDisk = accBag.takeObject({position = {-66,1,-15}, rotation = {0,90,0},scale={3.75,3.75,3.75}, guid = v.guid})
            dataDiskClone = dataDisk.clone()
            accBag.putObject(dataDiskClone)
            dataDisk.setTable("List",finalList)
            dataDisk.setName("New Disk")
            dataDisk.setLuaScript(cardLua)
            print("Done")
        end
    end
    initiate()
end


-- Builder first step: sets up basic list table and select faction.
function builderStart()
    self.clearButtons()
    partList = {}
    partList.Pilots = {}
    partList.Upgrades = {}
    partList.spawnCard = self
    availablePilots = {}
    availableUps = {}
    shipSlots = {}
    currentIndex = nil
    totalCost = nil
    self.createButton({click_function = 'Dummy1', function_owner = self, label = 'Choose Faction', position = {0,0.45,-0.3}, width = 1800, height = 520, font_size = 240,  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'buiZeo', function_owner = self, label = 'Zeon', position = {-0.6,0.45,0.1}, width = 1000, height = 380, font_size = 200,  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'buiFed', function_owner = self, label = 'Federation', position = {-0.6,0.45,0.4}, width = 1000, height = 380, font_size = 200,  scale = {0.25,0.25,0.25}})
end


-- One function for each faction, forwards to main menu.
function buiZeo()
    partList.Faction = 1
    mainMenu()
end

function buiFed()
    partList.Faction = 2
    mainMenu()
end

function initialSetUp()

end

-- Main Menu: shows wich ship is on the list, indicates how many points is dedicated to each ship.
-- Offers 3 options: reset (Back to initiate), add ship and spawn.
function mainMenu()
    totalCost = {}
    self.clearButtons()
    self.createButton({click_function = 'addShip', function_owner = self, label = 'Add Ship', position = {-0.45,0.45,-0.3}, width = 1300, height = 380, font_size = 200,  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'builderSpawn', function_owner = self, label = 'Spawn List', position = {0.45,0.45,-0.3}, width = 1300, height = 380, font_size = 200,  scale = {0.25,0.25,0.25}})
    for i, pilot in pairs(partList.Pilots) do
        local cost = pilot[3]
        for k,v in pairs (partList.Upgrades[i]) do
            if v[3]~= nil then
                cost = cost+v[3]
            end
        end
        self.createButton({click_function = 'selectShip'..i, function_owner = self, label = pilot[2]..' ('..cost..')', position = {-0.4,0.45,-0.2+i*0.15}, width = 1500, height = 300, font_size = 130,  scale = {0.25,0.25,0.25}})
        totalCost[i] = cost
    end
    listCost = 0
    for i, cost in pairs(totalCost) do
        listCost = listCost + cost
    end
    self.createButton({click_function = 'Dummy1', function_owner = self, label = 'List cost: '..listCost, position = {0.4,0.45,0.8}, width = 1300, height = 320, font_size = 150,  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'initiate', function_owner = self, label = 'RESET', position = {-0.5,0.45,0.8}, width = 1300, height = 320, font_size = 150,  scale = {0.25,0.25,0.25}})
end

-- Adding a ship will open a list of all available ship types.
function addShip()
    self.clearButtons()
    if partList.Pilots == nil then
        shipIndex = 1
    else
        shipIndex=1
        for i, pilot in pairs(partList.Pilots) do
            shipIndex = shipIndex + 1
        end
    end
    local modelIndex = 1
    local aux = 1
    local auxB = 0
    availableShips = {}
    for i, shipModel in pairs(masterShipDB) do
        for k, fac in pairs (shipModel['Fac']) do
            if  k == partList.Faction then
                Font=100
                availableShips[modelIndex] = i
                if aux > 7 then
                    aux=1
                    auxB=auxB+1
                end
                if string.len(i)>18 then
                    Font = 80
                end
                self.createButton({click_function = 'selectModel'..modelIndex, function_owner = self, label = shipModel['name'], position = {-0.52+auxB*0.6,0.45,aux*0.16-0.35}, width = 1000, height = 220, font_size = Font,  scale = {0.25,0.25,0.25}})
                aux = aux+1
                modelIndex=modelIndex+1
            end
        end
    end
end


function selectModelGeneric(arg)
    chosenModel = availableShips[arg]
    availableShips = {}
    self.clearButtons()
    availablePilots = {}

    local aux = 0
    local auxB = 0
    local index = 1
    for k, v in pairs(masterPilotDB) do
        if v['ship_type'] == chosenModel then
            if v['Faction']==partList.Faction then
                cost = v['cost']
                availablePilots[index] = {}
                availablePilots[index][1] = k
                availablePilots[index][2] = v['name']
                availablePilots[index][3] = cost
                self.createButton({click_function = 'setPilot'..index, function_owner = self, label = v['name']..' ('..cost..')', position = {-0.5+auxB,0.45,-0.2+aux*0.15}, width = 1600, height = 220, font_size = 125,  scale = {0.25,0.25,0.25}})
                aux= aux+1
                if aux>6 then
                    aux = 0
                    auxB = auxB+1
                end
                index = index+1
            end
        end
    end
    chosenModel = nil
end

--selecting a ship type will open a list of every pilot for that ship. MUST REWRITE! 18 ship types, with more to come. Each option should set a variable and call an unified function to spawn the pilot buttons!
function selectModel1()
    selectModelGeneric(1)
end

function selectModel2()
    selectModelGeneric(2)
end

function selectModel3()
    selectModelGeneric(3)
end

function selectModel4()
    selectModelGeneric(4)
end

function selectModel5()
    selectModelGeneric(5)
end

function selectModel6()
    selectModelGeneric(6)
end

function selectModel7()
    selectModelGeneric(7)
end

function selectModel8()
    selectModelGeneric(8)
end

function selectModel9()
    selectModelGeneric(9)
end

function selectModel10()
    selectModelGeneric(10)
end

function selectModel11()
    selectModelGeneric(11)
end

function selectModel12()
    selectModelGeneric(12)
end

function selectModel13()
    selectModelGeneric(13)
end

function selectModel14()
    selectModelGeneric(14)
end

function selectModel15()
    selectModelGeneric(15)
end

function selectModel16()
    selectModelGeneric(16)
end

function selectModel17()
    selectModelGeneric(17)
end

function selectModel18()
    selectModelGeneric(18)
end

function selectModel19()
    selectModelGeneric(19)
end

function selectModel20()
    selectModelGeneric(20)
end


-- Selecting a pilot will add ship model and pilot to part list, update max index and go back to main menu. MUST REWRITE! Each pilot option should set variables and call an unified function to set up the part list!
function setPilotGeneric(arg)
    self.clearButtons()
    partList.Pilots[shipIndex] = {}
    partList.Pilots[shipIndex][1] = availablePilots[arg][1]
    partList.Pilots[shipIndex][2] = availablePilots[arg][2]
    partList.Pilots[shipIndex][3] = availablePilots[arg][3]
    partList.Upgrades[shipIndex] = {}
    for ind, slot in pairs(masterPilotDB[availablePilots[arg][1]]['slot']) do
        partList.Upgrades[shipIndex][ind] = {}
        partList.Upgrades[shipIndex][ind][4]= slot        --id of the slot
        local slotNam = slotName[slot]
        partList.Upgrades[shipIndex][ind][5]= slotNam     --String of the Slot Name
        partList.Upgrades[shipIndex][ind][6]=false        --slot has been removed? T for yes, F for no
    end
    availablePilots = nil
    mainMenu()
end


function setPilot1()
    setPilotGeneric(1)
end

function setPilot2()
    setPilotGeneric(2)
end

function setPilot3()
    setPilotGeneric(3)
end

function setPilot4()
    setPilotGeneric(4)
end

function setPilot5()
    setPilotGeneric(5)
end

function setPilot6()
    setPilotGeneric(6)
end

function setPilot7()
    setPilotGeneric(7)
end

function setPilot8()
    setPilotGeneric(8)
end

function setPilot9()
    setPilotGeneric(9)
end

function setPilot10()
    setPilotGeneric(10)
end

function setPilot11()
    setPilotGeneric(11)
end

function setPilot12()
    setPilotGeneric(12)
end

function setPilot13()
    setPilotGeneric(13)
end

function setPilot14()
    setPilotGeneric(14)
end

function setPilot15()
    setPilotGeneric(15)
end

function builderSpawn()
    finalList = {}
    finalList.Pilots = {}
    for i, pilot in pairs(partList.Pilots) do
        finalList.Pilots[i] = pilot[1]
    end
    finalList.Faction = partList.Faction
    finalList.spawnCard = partList.spawnCard
    finalList.Upgrades = {}
    for i, upList in pairs(partList.Upgrades) do
        finalList.Upgrades[i] = {}
        for k, Up in pairs(upList) do
            table.insert(finalList.Upgrades[i], Up[1])
        end
    end
    idSpawner(finalList)
end

-- Selecting a ship that is on the main menu will show wich slots are empty and wich ones are taken, indicating how many points are being used on this ship and how many points the list as a whole is using.
-- To Do: Set up auxiliary table with slots and upgrades so the correct buttons are spawned. Stablishes variables for special cases (Froce Powers, dual slots). Show point costs of each ship and full squad.
function selectShipGeneric(arg)
    self.clearButtons()
    local aux = 1
    local auxB = 0
    shipIndex = arg -- constant for the select ship number
    local index = 1
    availableSlots = {}
    addedSlot={}
    lastSlot=0
    slotNum=0
    totalCost[shipIndex] = 0
    pilotId= partList.Pilots[shipIndex][1]
    pilotName= partList.Pilots[shipIndex][2]
    shipCost= partList.Pilots[shipIndex][3]
    shipSlots[shipIndex]={}


    --Adds all possible slots for given ship
    for k, v in pairs(partList.Upgrades[shipIndex]) do
        partList.Upgrades[shipIndex][k][6] = true
    end


    for k, v in pairs(masterPilotDB[pilotId]['slot']) do
        slotNum=slotNum+1
        partList.Upgrades[shipIndex][k][6]=false
        addedSlot[slotNum]=true
    end

    --Checks and adds slot for every upgrade that adds a slot
    for k, Upg in pairs(partList.Upgrades[shipIndex]) do
        if Upg[1] ~=nil then
            if masterUpgradesDB[Upg[1]]['addSlot'] ~= nil then
                for i, addSlot in pairs(masterUpgradesDB[Upg[1]]['addSlot']) do
                    slotNum=slotNum+1
                    if partList.Upgrades[shipIndex][slotNum] == nil then
                        partList.Upgrades[shipIndex][slotNum] = {}
                        partList.Upgrades[shipIndex][slotNum][4] = addSlot
                        partList.Upgrades[shipIndex][slotNum][5] = slotName[addSlot]
                        partList.Upgrades[shipIndex][slotNum][6] = false
                        addedSlot[slotNum]=true
                    else
                        partList.Upgrades[shipIndex][slotNum][6] = false
                    end
                end
            end
        end
    end

    for k, Upg in pairs(partList.Upgrades[shipIndex]) do
        if Upg[1] ~=nil then
            if masterUpgradesDB[Upg[1]]['remSlot'] ~= nil then
                for u, s in pairs (masterUpgradesDB[Upg[1]]['remSlot']) do
                    local rem = true
                    for i, v in pairs (partList.Upgrades[shipIndex]) do
                        if v[4] == s and rem ==true then
                            v[6]=true
                            rem=false
                        end
                    end
                end
            end
        end
    end

    for k, v in pairs(partList.Upgrades[shipIndex]) do
        if v[6]==true then
            v[1]=nil
            v[2]=nil
            v[3]=nil
        end
    end

    for i, slots in pairs(partList.Upgrades[shipIndex]) do
        if aux > 5 then
            aux = 1
            auxB = auxB+1
        end
        if partList.Upgrades[shipIndex][i][6] == true then

        elseif partList.Upgrades[shipIndex][i][1] == nil then
            self.createButton({click_function = 'selectSlot'..i, function_owner = self, label = partList.Upgrades[shipIndex][i][5], position = {-0.4+auxB*0.8,0.45,-0.22+aux*0.15}, width = 1500, height = 300, font_size = 120,  scale = {0.25,0.25,0.25}})
            aux=aux+1
        else
            self.createButton({click_function = 'selectSlot'..i, function_owner = self, label = partList.Upgrades[shipIndex][i][2]..' ('..partList.Upgrades[shipIndex][i][3]..')', position = {-0.4+auxB*0.8,0.45,-0.22+aux*0.15}, width = 1500, height = 300, font_size = 120,  scale = {0.25,0.25,0.25}})
            aux=aux+1
        end
        local index=index+1
    end

    for i, pilot in pairs(partList.Pilots) do
        local cost = pilot[3]
        for k,v in pairs (partList.Upgrades[i]) do
            if v[3]~= nil then
                cost = cost+v[3]
            end
        end
        totalCost[i] = cost
    end
    listCost = 0
    for i, cost in pairs(totalCost) do
        listCost = listCost + cost
    end

    self.createButton({click_function = 'Dummy1', function_owner = self, label = partList.Pilots[shipIndex][2]..' ('..partList.Pilots[shipIndex][3]..')', position = {-0.3,0.45,-0.35}, width = 2000, height = 320, font_size = 150,  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'mainMenu', function_owner = self, label = 'Back', position = { 0.5,0.45,-0.35}, width = 1000, height = 320, font_size = 150,  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'removeShip', function_owner = self, label = 'Remove Ship', position = { 0.6,0.45,0.75}, width = 1000, height = 320, font_size = 150,  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'Dummy1', function_owner = self, label = 'Ship cost: '..totalCost[shipIndex], position = {-0.6,0.45,0.8}, width = 1000, height = 220, font_size = 150,  scale = {0.25,0.25,0.25}})

    self.createButton({click_function = 'Dummy1', function_owner = self, label = 'List cost: '..listCost, position = {0,0.45,0.8}, width = 1000, height = 220, font_size = 150,  scale = {0.25,0.25,0.25}})
end

function removeShip()
    partList.Pilots[shipIndex] = nil
    partList.Upgrades[shipIndex] = nil
    totalCost[shipIndex] = nil
    for i, index in pairs(partList.Pilots) do
        if i > shipIndex then
            partList.Pilots[i-1] = partList.Pilots[i]
            partList.Pilots[i] = nil
            partList.Upgrades[i-1] = partList.Upgrades[i]
            partList.Upgrades[i] = nil
            totalCost[i-1] = totalCost[i]
            totalCost[i] = nil
        end
    end
    mainMenu()
end

function selectShip1()
    selectShipGeneric(1)
end

function selectShip2()
    selectShipGeneric(2)
end

function selectShip3()
    selectShipGeneric(3)
end

function selectShip4()
    selectShipGeneric(4)
end

function selectShip5()
    selectShipGeneric(5)
end

function selectShip6()
    selectShipGeneric(6)
end

function selectShip7()
    selectShipGeneric(7)
end

function selectShip8()
    selectShipGeneric(8)
end

function selectSlotGeneric(slotIndex)
    self.clearButtons()
    slotId = partList.Upgrades[shipIndex][slotIndex][4]             -- Value tied for this function!
    currSlotInd = slotIndex
    local index = 1
    local aux = 1
    local auxB = 0
    acailableUps = {}
    self.createButton({click_function = 'selectUpNone', label = 'None (0)', function_owner = self, position = {-0.45+auxB*0.6,0.45,-0.2}, width = 1500, height = 220, font_size = 120,  scale = {0.25,0.25,0.25}})
    for id, up in pairs(masterUpgradesDB) do
        if up['slot'] == slotId then
            local validUp=true
            if up['restriction']['Faction'] ~= nil then
                if up['restriction']['Faction'][partList.Faction]~=true then
                    validUp=false
                end
            end
            if up['restriction']['Size'] ~= nil then
                if up['restriction']['Size'][masterShipDB[masterPilotDB[partList.Pilots[shipIndex][1]]['ship_type']]['size']]~=true then
                    validUp=false
                end
            end
            if up['restriction']['ship'] ~= nil then
                if up['restriction']['ship'][masterPilotDB[partList.Pilots[shipIndex][1]]['ship_type']] ~= true then
                    validUp=false
                end
            end
            if validUp == true then
                if up['cost'] =='a' then
                    sAgi =   masterShipDB[masterPilotDB[ partList.Pilots[shipIndex][1] ]['ship_type'] ]['agi']
                    upCost = varCostA[id][sAgi]
                elseif up['cost'] == 's' then
                    sSize =   masterShipDB[masterPilotDB[ partList.Pilots[shipIndex][1] ]['ship_type'] ]['size']
                    upCost = varCostS[id][sSize]
                elseif up['cost'] == 'i' then
                    pInit = masterPilotDB[partList.Pilots[shipIndex][1]]['init']
                    upCost = varCostI[id][pInit]
                else
                    upCost = up['cost']
                end
                availableUps[index] = {[1]=id, [2]=up['name'], [3]=upCost}
                self.createButton({click_function = 'selectUp'..index, label = up['name']..' ('..upCost..')', function_owner = self, position = {-0.53+auxB*0.58,0.45,aux*0.1-0.1}, width = 1100, height = 200, font_size = 100,  scale = {0.25,0.25,0.25}})
                aux=aux+1
                index = index+1
                if aux > 8 then
                    aux=1
                    auxB=auxB+1
                end
                validUp= false
            end
        elseif slotId == 99 then
            local hpCheck={[3]=true,[5]=true,[6]=true}
            if hpCheck[up['slot']] == true then
                availableUps[index] = {[1]=id, [2]=up['name'], [3]=up['cost']}
                self.createButton({click_function = 'selectUp'..index, label = up['name']..' ('..up['cost']..')', function_owner = self, position = {-0.53+auxB*0.58,0.45,aux*0.1-0.1}, width = 1100, height = 200, font_size = 100,  scale = {0.25,0.25,0.25}})
                aux=aux+1
                index = index+1
                if aux > 8 then
                    aux=1
                    auxB=auxB+1
                end
            end
        end

    end

    self.createButton({click_function = 'backFromSelectUp', function_owner = self, label = 'Back', position = { 0.5,0.45,-0.35}, width = 1000, height = 320, font_size = 150,  scale = {0.25,0.25,0.25}})
end


function backFromSelectUp()
        if shipIndex == 1 then
            selectShip1()
        elseif shipIndex == 2 then
            selectShip2()
        elseif shipIndex == 3 then
            selectShip3()
        elseif shipIndex == 4 then
            selectShip4()
        elseif shipIndex == 5 then
            selectShip5()
        elseif shipIndex == 6 then
            selectShip6()
        elseif shipIndex == 7 then
            selectShip7()
        elseif shipIndex == 8 then
            selectShip8()
        end
    end

function selectSlot1()
    selectSlotGeneric(1)
end

function selectSlot2()
    selectSlotGeneric(2)
end

function selectSlot3()
    selectSlotGeneric(3)
end

function selectSlot4()
    selectSlotGeneric(4)
end

function selectSlot5()
    selectSlotGeneric(5)
end

function selectSlot6()
    selectSlotGeneric(6)
end

function selectSlot6()
    selectSlotGeneric(6)
end

function selectSlot7()
    selectSlotGeneric(7)
end

function selectSlot8()
    selectSlotGeneric(8)
end

function selectSlot9()
    selectSlotGeneric(9)
end

function selectSlot10()
    selectSlotGeneric(10)
end

function selectSlot11()
    selectSlotGeneric(11)
end

function selectSlot12()
    selectSlotGeneric(12)
end

function selectSlot13()
    selectSlotGeneric(13)
end

function selectSlot14()
    selectSlotGeneric(14)
end

function selectSlot14()
    selectSlotGeneric(14)
end

function selectSlot15()
    selectSlotGeneric(15)
end

function selectSlot16()
    selectSlotGeneric(16)
end

function selectSlot17()
    selectSlotGeneric(17)
end

function selectSlot18()
    selectSlotGeneric(18)
end

function selectSlot19()
    selectSlotGeneric(19)
end

function selectSlot99()
    selectSlotGeneric(99)
end


function selectUpNone()
    partList.Upgrades[shipIndex][currSlotInd][1] = nil     --first '1' tied to selectUp1, second value indicate the names
    partList.Upgrades[shipIndex][currSlotInd][2] = nil
    partList.Upgrades[shipIndex][currSlotInd][3] = nil
    if shipIndex == 1 then
        selectShip1()
    elseif shipIndex == 2 then
        selectShip2()
    elseif shipIndex == 3 then
        selectShip3()
    elseif shipIndex == 4 then
        selectShip4()
    elseif shipIndex == 5 then
        selectShip5()
    elseif shipIndex == 6 then
        selectShip6()
    elseif shipIndex == 7 then
        selectShip7()
    elseif shipIndex == 8 then
        selectShip8()
    end
end

function selectUpGeneric(arg)
    partList.Upgrades[shipIndex][currSlotInd][1] = availableUps[arg][1]      --first '1' tied to selectUp1, second value indicate the Id
    partList.Upgrades[shipIndex][currSlotInd][2] = availableUps[arg][2]      --first '1' tied to selectUp1, second value indicate the Name
    partList.Upgrades[shipIndex][currSlotInd][3] = availableUps[arg][3]      --first '1' tied to selectUp1, second value indicate the cost
    if shipIndex == 1 then
        selectShip1()
    elseif shipIndex == 2 then
        selectShip2()
    elseif shipIndex == 3 then
        selectShip3()
    elseif shipIndex == 4 then
        selectShip4()
    elseif shipIndex == 5 then
        selectShip5()
    elseif shipIndex == 6 then
        selectShip6()
    elseif shipIndex == 7 then
        selectShip7()
    elseif shipIndex == 8 then
        selectShip8()
    end
end

function selectUp1()
    selectUpGeneric(1)
end

function selectUp2()
    selectUpGeneric(2)
end

function selectUp3()
    selectUpGeneric(3)
end

function selectUp4()
    selectUpGeneric(4)
end

function selectUp5()
    selectUpGeneric(5)
end

function selectUp6()
    selectUpGeneric(6)
end

function selectUp7()
    selectUpGeneric(7)
end

function selectUp8()
    selectUpGeneric(8)
end

function selectUp9()
    selectUpGeneric(9)
end

function selectUp10()
    selectUpGeneric(10)
end

function selectUp11()
    selectUpGeneric(11)
end

function selectUp12()
    selectUpGeneric(12)
end

function selectUp13()
    selectUpGeneric(13)
end

function selectUp14()
    selectUpGeneric(14)
end

function selectUp15()
    selectUpGeneric(15)
end

function selectUp16()
    selectUpGeneric(16)
end

function selectUp17()
    selectUpGeneric(17)
end

function selectUp18()
    selectUpGeneric(18)
end

function selectUp19()
    selectUpGeneric(19)
end

function selectUp20()
    selectUpGeneric(20)
end

function selectUp21()
    selectUpGeneric(21)
end

function selectUp22()
    selectUpGeneric(22)
end

function selectUp23()
    selectUpGeneric(23)
end

function selectUp24()
    selectUpGeneric(24)
end

function selectUp25()
    selectUpGeneric(25)
end

function selectUp26()
    selectUpGeneric(26)
end

function selectUp27()
    selectUpGeneric(27)
end

function selectUp28()
    selectUpGeneric(28)
end





-- List Spawner starts here
-- First step: Create the table that ultimately will be provided to newSpawner. Then, inquires player wich faction his list belongs to.
function spawnerStart ()
    self.clearButtons()
    finalList = {}
    finalList.Pilots = {}
    finalList.Upgrades = {}
    finalList.Faction = 0
    finalList.Aux = {}
    finalList.AuxU = {}
    finalList.spawnCard = self
    self.createButton({click_function = 'Dummy1', function_owner = self, label = 'Choose Faction', position = {0,0.45,-0.3}, width = 1800, height = 520, font_size = 240,  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'Zeo', function_owner = self, label = 'Zeon', position = {-0.4,0.45,0}, width = 1200, height = 280, font_size = 200,  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'Fed', function_owner = self, label = 'Federation', position = {-0.4,0.45,0.2}, width = 1200, height = 280, font_size = 200,  scale = {0.25,0.25,0.25}})

    self.createButton({click_function = 'initiate', function_owner = self, label = 'Back', position = {0.55,0.45,0.75}, width = 900, height = 320, font_size = 180,  scale = {0.25,0.25,0.25}})
end

--Set up faction in the table
function Zeo()
    finalList.Faction = 1
    inputList()
end

function Fed()
    finalList.Faction = 2
    inputList()
end

-- Dummy functions for label buttons
function Dummy()
end

function Dummy1()
    print('Please pick a faction')
end

function Dummy2()
    print('Please choose a ship for this pilot:')
end

function Dummy3()
    print('Please type or paste your list. Refer to the manual if help is needed formating the list!')
end

function Dummy4()
    print('Please choose a slot for this upgrade card:')
end

-- Second step: Create the input field where the list should be pasted/typed. Offers a button to spawn the list and a button to save to a data disk (FEATURE NOT IMPLEMENTED YET)
function inputList()
    savingList=false
    self.clearButtons()
    self.createButton({click_function = 'Dummy3', function_owner = self, label = 'Please type or paste your list', position = {-0,0.45,-0.4}, width = 2500, height = 280, font_size = 200, scale = {0.4,0.4,0.4}, tooltip = 'Click here to spawn yout list',  scale = {0.25,0.25,0.25}})
    --self.createButton({click_function = 'printInput', function_owner = self, label = 'print', position = {-0.5,0.45,-1}, width = 800, height = 240, font_size = 100, scale = {0.4,0.4,0.4}, tooltip = 'Click here to spawn yout list',  scale = {0.25,0.25,0.25}})
    self.createInput({input_function = 'action', function_owner = self, position = {0,0.45,0.12}, width = 3200, height = 1600, font_size = 200, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'validCheck', function_owner = self, label = 'Spawn List', position = {-0.5,0.45,0.7}, width = 1400, height = 400, font_size = 200, scale = {0.4,0.4,0.4}, tooltip = 'Click here to spawn yout list',  scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'saveList', function_owner = self, label = 'Save to Disk', position = {0.5,0.45,0.7}, width = 1400, height = 400, font_size = 200, scale = {0.4,0.4,0.4}, tooltip = 'Click here to save your list in a data disk', scale = {0.25,0.25,0.25}})
end

-- This function is supposed to store the list in the script of the data disk object and set up a button wich will spawn the stored list calling the list parser and providing the string.
-- The disk can be saved in the TTS chest for easy retrieval. Could it be set up in a way to store and spawn several lists?

function saveList()
    print('Saving List')
    savingList = true
    validCheck()
end

-- print function to test the input
function printInput()
    print(lista)
    lista = string.gsub(lista, 'v2', '')
    print(lista)
end

-- Checks if the input is a valid string. If it is, call the list parser. If not, returns to the input list.
function validCheck()
    if lista == '' then
        Dummy3()
        inputList()
    else
        parseList()
    end
end

pilotsWithDash = {}
pilotsWithDash["g4r-gor v"] = true
pilotsWithDash["g4r-g0r v"] = true

alternateSpelling = {}
alternateSpelling["servomotor s-foils"] = 'Servomotor S-Foils (Open)'
alternateSpelling["pivot wing"] = 'Pivot Wing (Open)'
alternateSpelling["integrated s-foils"] = 'Integrated S-Foils (Open)'
alternateSpelling["grappling struts"] = 'Grappling Struts (Open)'
alternateSpelling["landing struts"] = 'Landing Struts (Open)'
alternateSpelling["stabilized s-foils"] = 'Stabilized S-Foils (Open)'
alternateSpelling["0-66"] = 'O-66'
alternateSpelling["g4r-gor v/m"] = 'G4R-G0R V/M'

-- Third Step: This function will decompose the input string and will propperly alocate each value on the propper position in the table.
-- Then, it calls for the next function, either inquiring for ships and version of upgrades or calling the spawner.
    function parseList()
        self.clearButtons()
        self.clearInputs()
        if lista ~= nil then
            parsedList = {}
            pilotsList = mysplit(lista, '/', true)
            local rest = ""
            for i, pilot in ipairs(pilotsList) do
                pilot = rest .. pilot
                if pilotsWithDash[string.lower(pilot)] ~= nil then
                    rest = pilot .. "/"
                else
                    table.insert(parsedList, mysplit(pilot,'+', true))
                    rest = ""
                end
            end
            pilotIndex = 0
            Aux = 0
            for i, pilot in ipairs(parsedList) do
                pilotIndex = pilotIndex + 1
                for k, cardN in ipairs(pilot) do
                    cardN = string.gsub(cardN, 'Hardpoint: ', '')
                    if alternateSpelling[string.lower(cardN)] ~= nil then
                        cardN = alternateSpelling[string.lower(cardN)]
                    end
                    if k == 1 then -- First card, the pilot
                        finalList.Aux[pilotIndex] = {}
                        finalList.AuxU[pilotIndex] = {}
                        local found = false
                        for id, pilot in pairs(masterPilotDB) do
                            if string.lower(pilot['name']) == string.lower(cardN) and pilot['Faction'] == finalList.Faction then
                                Aux = Aux + 1
                                finalList.Aux[pilotIndex][Aux] = id
                                finalList.Upgrades[pilotIndex] = {}
                                found = true
                            end
                        end
                        if not found then
                            printToAll("Unable to find pilot: " .. cardN .. " please check correct spelling", {1,0,0})
                            pilotIndex = pilotIndex - 1
                            break
                        end
                        if Aux == 1 then
                            finalList.Pilots[pilotIndex] = finalList.Aux[pilotIndex][1]
                            finalList.Aux[pilotIndex] = nil
                        end
                        Aux = 0
                    else -- The remaining cards, the upgrades
                        finalList.AuxU[pilotIndex][k] ={}
                        local found = false
                        for id, upg in pairs(masterUpgradesDB) do
                            if string.lower(upg['name']) == string.lower(cardN) then
                                found = true
                                if upg['restriction']['Faction'] == nil or upg['restriction']['Faction'][finalList.Faction] == true then
                                    Aux = Aux + 1
                                    finalList.AuxU[pilotIndex][k][Aux] = id
                                else
                                    printToAll('Upgrade "'.. cardN .. '" is restricted to another faction', {1,0,0})
                                end
                            end
                        end
                        if not found then
                            printToAll("Unable to find upgrade: " .. cardN .. " please check correct spelling", {1,0,0})
                            goto continue
                        end
                        if Aux == 1 then
                            finalList.Upgrades[pilotIndex][k-1] = finalList.AuxU[pilotIndex][k][Aux]
                            finalList.AuxU[pilotIndex][k] = nil
                        end
                        Aux = 0
                    end -- if Pilot and upgrade
                    ::continue::
                end -- for card
            end
            pChecker()
        else
            Dummy3()
            initiate()
        end
    end


-- Fourth step: This function checks for pilots with the same name in the same faction and stores de data por future inquire. If no inquire is needed, it calls the newSpawner function and reset all buttons.
function pChecker()
    repPN=0
    for i, pilot in pairs(finalList.Aux) do
        currPIndex = i
        repPL = {}
        for k, v in pairs(pilot) do
            repPL[k] = v
            repPN=repPN+1
        end
        pilot = nil
    end
    if repPN ~= 0 then
        pilotChoice(repPL)
    else
        uChecker()
    end
end

function uChecker()
    repUN=0
    repUL = {}
    for pilot, s in pairs(finalList.AuxU) do
        repUL[pilot] = {}
        for slot, up in pairs(s) do
            currIndex = pilot
            currSlot = slot
            repUL[pilot][currSlot] = {}
            for k,v in pairs(up) do
                repUL[pilot][slot][k] = v
                repUN=repUN+1
            end
        end
    end
    if repUN == 0 then
        repUL = nil
    end

    if repUN ~= 0 then
        upChoice(repUL)
    else
        idSpawner(finalList)
    end
end

-- luke skywalker+sense
-- luke skywalker + r2-d2
-- lando calrissian+han solo
-- sabine wren/luke skywalker + r2-d2
-- sabine wren/norra wexley+r2-d2
-- norra wexley+r2-d2/sabine wren
-- luke skywalker + r2-d2/sabine wren

-- Fifth Step: If pilots with several options of ships are present, for each pilot will create an inquire asking wich ship the pilot is in.
function pilotChoice(options)
    local name = (masterPilotDB[options[1]]['name'])
    local button1 = name..' ('.. masterShipDB[masterPilotDB[options[1]]['ship_type']]['name'] ..')'
    local button2 = name..' ('.. masterShipDB[masterPilotDB[options[2]]['ship_type']]['name'] ..')'
    self.clearButtons()
    self.createButton({click_function = 'Dummy2', function_owner = self, label = 'Please choose a ship for the following pilot', position = {0,0.45,-0.4}, width = 3400, height = 380, font_size = 170, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'Dummy2', function_owner = self, label = name, position = {0,0.45,-0.1}, width = 1600, height = 380, font_size = 200, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'setShip1', function_owner = self, label = button1, position = {0,0.45,0.1}, width = 2500, height = 380, font_size = 160, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'setShip2', function_owner = self, label = button2, position = {0,0.45,0.3}, width = 2500, height = 380, font_size = 160, scale = {0.25,0.25,0.25}})
    if #options == 3 then
        local button3 = name..' ('.. masterShipDB[masterPilotDB[options[3]]['ship_type']]['name'] ..')'
        self.createButton({click_function = 'setShip3', function_owner = self, label = button3, position = {0,0.45,0.5}, width = 2500, height = 380, font_size = 180, scale = {0.25,0.25,0.25}})
    end
end



-- Stores the ship option for each pilot if needed. If there is no other inquire needed, will call upgrade inquire if need, if not, will call the newSpawner function.
function setShip1()
    finalList.Pilots[currPIndex] = repPL[1]
    finalList.Aux[currPIndex] = nil
    repPL = nil
    repPN= 0
    repUN= 0
    currPIndex = nil
    pChecker()
end

function setShip2()
    finalList.Pilots[currPIndex] = repPL[2]
    finalList.Aux[currPIndex] = nil
    repPL = nil
    repPN= 0
    repUN= 0
    currPIndex = nil
    pChecker()
end

function setShip3()
    finalList.Pilots[currPIndex] = repPL[3]
    finalList.Aux[currPIndex] = nil
    repPL = nil
    repPN= 0
    repUN= 0
    currPIndex = nil
    pChecker()
end

slotName = {}
slotName[1] = 'Talent' -- EPT
slotName[2] = 'Sensors' -- Sensor
slotName[3] = 'Cannon' -- Cannon
slotName[4] = 'Turret' -- Turret
slotName[5] = 'Torpedo' -- Torpedo
slotName[6] = 'Missile' -- Missile
slotName[7] = '' --
slotName[8] = 'Crew' -- Crew
slotName[9] = ''
slotName[10] = 'Astromech' --Astromech
slotName[11] = ''
slotName[12] = 'Device' -- Device
slotName[13] = 'Illicit' -- Ilicit
slotName[14] = 'Modification' -- Modification
slotName[15] = 'Title' -- Title
slotName[16] = 'Gunner' -- Gunner
slotName[17] = 'Force Talent' -- Force Power
slotName[18] = 'Configuration' -- Configuration
slotName[19] = 'Tech' -- Tech
slotName[20] = 'Relay' -- Relay
slotName[99] = 'HardPoint' -- Hardpoint



-- Sixth Step: If Upgrades with several options in the same faction are present, for each upgrade will create an inquire asking wich slot the upgrade is in.
function upChoice(options)
    local name = (masterUpgradesDB[options[currIndex][currSlot][1]]['name'])
    local Up1 = slotName[masterUpgradesDB[options[currIndex][currSlot][1]]['slot']]
    local Up2 = slotName[masterUpgradesDB[options[currIndex][currSlot][2]]['slot']]
    self.clearButtons()
    self.createButton({click_function = 'Dummy4', function_owner = self, label = 'Please choose a slot for the following upgrade', position = {0,0.45,-0.4}, width = 3400, height = 380, font_size = 170, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'Dummy4', function_owner = self, label = name, position = {0,0.45,-0.1}, width = 1600, height = 380, font_size = 200, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'setUp1', function_owner = self, label = Up1, position = {0,0.45,0.1}, width = 1200, height = 380, font_size = 180, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'setUp2', function_owner = self, label = Up2, position = {0,0.45,0.3}, width = 1200, height = 380, font_size = 180, scale = {0.25,0.25,0.25}})
    if options == 3 then
        local Up3 = slotName[masterUpgradesDB[options[currIndex][currSlot][3]]['slot']]
        self.createButton({click_function = 'setUp3', function_owner = self, label = Up3, position = {0,0.45,0.8}, width = 1200, height = 380, font_size = 180, scale = {0.25,0.25,0.25}})
    end
end

function setUp1()
    finalList.Upgrades[currIndex][currSlot-1] = finalList.AuxU[currIndex][currSlot][1]
    finalList.AuxU[currIndex][currSlot] = nil
    repUL = nil
    repUN= 0
    currSlot = nil
    currIndex = nil
    uChecker()
end

function setUp2()
    finalList.Upgrades[currIndex][currSlot-1] = finalList.AuxU[currIndex][currSlot][2]
    finalList.AuxU[currIndex][currSlot] = nil
    repUL = nil
    repUN= 0
    currSlot = nil
    currIndex = nil
    uChecker()
end

function setUp3()
    finalList.Upgrades[currIndex][currSlot-1] = finalList.AuxU[currIndex][currSlot][3]
    finalList.AuxU[currIndex][currSlot] = nil
    repUL = nil
    repUN= 0
    currSlot = nil
    currIndex = nil
    uChecker()
end

variableCostSizeDB={}
variableCostSizeDB['engine upgrade'] = {['Small'] = 3, ['Medium'] = 6,['Large'] = 9}
variableCostSizeDB['expert handling'] = {['Small'] = 2, ['Medium'] = 3,['Large'] = 4}

variableCostAgiDB={}
variableCostAgiDB['hull upgrade'] = {[0] = 3,[1] = 4,[2] = 6,[3] = 8}
variableCostAgiDB['shield upgrade'] = {[0] = 3,[1] = 4,[2] = 6,[3] = 8}
variableCostAgiDB['stealth device'] = {[0] = 3,[1] = 4,[2] = 6,[3] = 8}

-- This function reads the list and informs the point cost of each ship, as well as the total point cost of the list, and offers the option either to cancel (and restorat) or to spawn the list.
function spawnCaller(arg)
    self.clearButtons()
    local aux = 0
    local auxB= 0
    local index = 1
    local cost = {}
    totalCost=0
    self.createButton({click_function = 'spawnProxy', function_owner = self, label = 'Spawn', position = {0,0.45,-0.4}, width = 1200, height = 380, font_size = 180, scale = {0.25,0.25,0.25}})
    for i, pilot in ipairs(arg.Pilots) do
        for k, pilots in pairs(shipPilotsDB[arg.Faction][arg.Ship[i]]) do
            if string.lower(pilot) == string.lower(k) then
                cost[i] = pilots['Cost']
            end
        end
        for k, ups in ipairs(arg.Upgrades[index]) do
            for x, slot in pairs(UpDB[arg.Faction]) do
                for z, up in pairs(UpDB[arg.Faction][x]) do
                    if string.lower(z) == string.lower(ups) then
                        cost[i] = cost[i]+up
                    end
                end
            end
            if variableCostSizeDB[string.lower(ups)] ~= nil then
                local size = shipPilotsDB[arg.Faction][arg.Ship[index] ]['Base']
                cost[i] = cost[i]+variableCostSizeDB[string.lower(ups)][size]
            elseif variableCostAgiDB[string.lower(ups)] ~= nil then
                local agi = shipPilotsDB[arg.Faction][arg.Ship[index] ]['Agility']
                cost[i] = cost[i]+variableCostAgiDB[string.lower(ups)][agi]
            else
                for x, slot in pairs(UpDB['Neu']) do
                    for z, up in pairs(UpDB['Neu'][x]) do
                        if string.lower(z) == string.lower(ups) then
                            cost[i] = cost[i]+up
                        end
                    end
                end
            end
        end
        self.createButton({click_function = 'Dummy', function_owner = self, label = arg.Pilots[i]..' ('..cost[i]..')', position = {-0.45+auxB*0.96,0.45,0.15*aux-0.2}, width = 1800, height = 250, font_size = 135, scale = {0.25,0.25,0.25}})
        aux=aux+1
        if aux>3 then
            aux=0
            auxB=1
        end
        index=index+1
        totalCost=totalCost+cost[i]
    end
    self.createButton({click_function = 'Dummy', function_owner = self, label = 'Total Cost ('..totalCost..')', position = {0,0.45,0.6}, width = 1800, height = 250, font_size = 150, scale = {0.25,0.25,0.25}})
    self.createButton({click_function = 'initiate', function_owner = self, label = 'Cancel', position = {0.5,0.45,0.75}, width = 1800, height = 250, font_size = 150, scale = {0.25,0.25,0.25}})

end

function spawnProxy()
    spawnNow(finalList)
end

-- Calls the newSpawner, wich will set up a propper postition for the spawning ships (POSITION NEEDS TO BE REFERCENCED TO SELF, NOT GLOBAL)
function spawnNow(arg)
    storePos = self.getPosition()
    pos = LocalPos(self, {3.5, 1, 4})
    rot = self.getRotation()
    self.setPosition(pos)
    self.setRotation({0,rot.y,rot.z})
    Global.call('newSpawner', arg)
    self.setPosition(storePos)
    self.setRotation(rot)
    initiate()
end


-- String split function
function mysplit(inputstr, sep, trim)
    if inputstr ~= nil then
        if sep == nil then
          sep = "%s"
        end
        local t={}
        for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
            if trim then
                str = str:match'^%s*(.*%S)' or ''
            end
            if str ~= "" then
                table.insert(t, str)
            end
        end
        return t
    end
end




-------
-- Local Reference function, for spawning items relative to the quick build card
function LocalPos(object, position)
    local rot = object.getRotation()
    local lPos = {position[1], position[2], position[3]}
    -- Z-X-Y extrinsic
    local zRot = RotMatrix('z', rot['z'])
    lPos = RotateVector(zRot, lPos)
    local xRot = RotMatrix('x', rot['x'])
    lPos = RotateVector(xRot, lPos)
    local yRot = RotMatrix('y', rot['y'])
    lPos = RotateVector(yRot, lPos)

    return Vect_Sum(lPos, object.getPosition())
end



function RotMatrix(axis, angDeg)
    local ang = math.rad(angDeg)
    local cs = math.cos
    local sn = math.sin

    if axis == 'x' then
        return {
                    { 1,        0,             0 },
                    { 0,   cs(ang),   -1*sn(ang) },
                    { 0,   sn(ang),      cs(ang) }
               }
    elseif axis == 'y' then
        return {
                    {    cs(ang),   0,   sn(ang) },
                    {          0,   1,         0 },
                    { -1*sn(ang),   0,   cs(ang) }
               }
    elseif axis == 'z' then
        return {
                    { cs(ang),   -1*sn(ang),   0 },
                    { sn(ang),      cs(ang),   0 },
                    { 0,                  0,   1 }
               }
    end
end

-- Apply given rotation matrix on given vector
-- (multiply matrix and column vector)
function RotateVector(rotMat, vect)
    local out = {0, 0, 0}
    for i=1,3,1 do
        for j=1,3,1 do
            out[i] = out[i] + rotMat[i][j]*vect[j]
        end
    end
    return out
end

-- Sum of two vectors (of any size)
function Vect_Sum(vec1, vec2)
    local out = {}
    local k = 1
    while vec1[k] ~= nil and vec2[k] ~= nil do
        out[k] = vec1[k] + vec2[k]
        k = k+1
    end
    return out
end

------
